# Ref. http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
    - 2.6
    - 2.7
#    - 3.3
#    - 3.4
install:
    - if [[ $TRAVIS_PYTHON_VERSION < '2.7' ]]; then pip install -r pkg/test_requirements-py-2.6.txt; else pip install -r pkg/test_requirements.txt; fi
env:
  - WITH_COVERAGE=1
script:
    - "./pkg/runtest.sh"
after_success:
  - coveralls
notifications:
    email:
        recipients:
            - satoru.satoh+github@gmail.com
        on_failure: always
